"""0003 add surname to author

Revision ID: 598457b5f5b1
Revises: a3d746c6b636
Create Date: 2024-10-06 10:33:40.320494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '598457b5f5b1'
down_revision = 'a3d746c6b636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_authors_surname'), ['surname'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authors_surname'))

    # ### end Alembic commands ###
